import img1 from "../assets/artist/arijit-singh.webp"
import img2 from "../assets/artist/kk.png"
import song1 from "../assets/songs/sapne-khule-296457 (1).mp3"
import song2 from "../assets/songs/sapne-khule-296457.mp3"

export const songs = [
  {
    id: 1,
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: true,
  },
  {
    id: 2,
    title: "Tadap Tadap",
    artist: "KK",
    playlist: "Heart & Soul by KK",
    coverArt: img2,
    audioSrc: song2,
    isFavorite: true,
  },
  {
    id: 3,
    title: "Channa Mereya",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: false,
  },
  {
    id: 4,
    title: "Yaaron",
    artist: "KK",
    playlist: "Heart & Soul by KK",
    coverArt: img2,
    audioSrc: song2,
    isFavorite: false,
  },
  {
    id: 5,
    title: "Raabta",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: true,
  },
  {
    id: 6,
    title: "Pal",
    artist: "KK",
    playlist: "Heart & Soul by KK",
    coverArt: img2,
    audioSrc: song2,
    isFavorite: false,
  },
  {
    id: 7,
    title: "Muskurane",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: true,
  },
  {
    id: 8,
    title: "Dus Bahane",
    artist: "KK",
    playlist: "Heart & Soul by KK",
    coverArt: img2,
    audioSrc: song2,
    isFavorite: true,
  },
  {
    id: 9,
    title: "Phir Bhi Tumko Chaahunga",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: false,
  },
  {
    id: 10,
    title: "Zindagi Do Pal Ki",
    artist: "KK",
    playlist: "Heart & Soul by KK",
    coverArt: img2,
    audioSrc: song2,
    isFavorite: false,
  },
  {
    id: 11,
    title: "Agar Tum Saath Ho",
    artist: "Arijit Singh",
    playlist: "Heartstrings by Arijit",
    coverArt: img1,
    audioSrc: song1,
    isFavorite: false,
  },
];
